### ISSUE TITLE
[US] En tant qu'Administrateur, je souhaite pouvoir changer le rôle d'un utilisateur

### ISSUE THREAD

**Issue by millehorde** [timAdrien/blog-api-nestJS#30]
<a href="https://github.com/millehorde"><img src="https://avatars1.githubusercontent.com/u/23100432?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [millehorde](https://github.com/millehorde)**
_Thursday Jan 10, 2019 at 21:44 GMT_
_Originally opened as https://github.com/millehorde/BlogSpec/issues/31_

----

Un Administrateur doit pouvoir changer le rôle d'un autre utilisateur.

Il peut :
```typescript
changer un auteur en blogger => les articles de l'auteur reste, il perd juste l'accès à l'édition de ceux-ci

changer un auteur en administrateur

changer un blogger en auteur

changer un blogger en administrateur
```

Il ne peut pas: 
```
changer de droit un autre administrateur sauf si l'administrateur en question est lui-même
```

**Related EPIC:** #11

**Comment by timAdrien** [comment]
done in previous commit, tests will be committed in next commit
