### ISSUE TITLE
[US] En tant qu'Auteur, je souhaite pouvoir récupérer la liste de tous mes articles

### ISSUE THREAD

**Issue by millehorde** [timAdrien/blog-api-nestJS#41]
<a href="https://github.com/millehorde"><img src="https://avatars1.githubusercontent.com/u/23100432?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [millehorde](https://github.com/millehorde)**
_Thursday Jan 10, 2019 at 22:49 GMT_
_Originally opened as https://github.com/millehorde/BlogSpec/issues/41_

----

Cette feature consiste à retourner la liste des articles créés par un Auteur.

Cette liste est composée d'entité Article, trié du plus récent au plus ancien.

_**Only for advanced developers**_
*(Une pagination est nécessaire pour aller au devant de grandes listes.)*

**Related EPIC:** #9

**Comment by timAdrien** [comment]
le tri sera fait dans la prochaine pull request
